#!/bin/bash

echo "Running: video_control.py &"
python video_control.py&

sudo SDL_VIDEODRIVER=fbcon SDL_FBDEV=/dev/fb1 mplayer -input file=/home/pi/lab1/video_fifo -vo sdl -framedrop /home/pi/bigbuckbunny320p.mp4
