#!/bin/bash

#run in the background
echo "Running: more_video_control_cb.py &"
python more_video_control_cb.py&

#call mplayer
sudo SDL_VIDEODRIVER=fbcon SDL_FBDEV=/dev/fb1 mplayer -input file=/home/pi/lab1/video_fifo -vo sdl -framedrop /home/pi/bigbuckbunny320p.mp4
